---
- name: install nginx
  hosts: nginx
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: Install nginx
      include_role:
        name: nginx
      vars:
        ansible_become: true
    
    - name: Configure NGINX
      include_role:
        name: nginx_config
      vars:
        ansible_become: true
        nginx_config_upload_ssl_enable: true
        nginx_config_upload_ssl_crt:
          - src: molecule/common/files/ssl/molecule.crt
            dest: /etc/ssl/certs
            backup: true
        nginx_config_upload_ssl_key:
          - src: molecule/common/files/ssl/molecule.key
            dest: /etc/ssl/private
            backup: true
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            deployment_location: /etc/nginx/conf.d/default.conf
            config:
              servers:
                # -- PROMETHEUS
                - core:
                    listen:
                      - port: 443
                        ssl: true
                        http2: true
                    server_name:
                      - "{{ alias_prometheus }}"
                  ssl:
                    certificate:
                      - /etc/ssl/certs/molecule.crt
                    certificate_key:
                      - /etc/ssl/private/molecule.key
                    protocols:
                      - TLSv1.2
                      - TLSv1.3
                    ciphers:
                      - ECDHE-ECDSA-AES128-GCM-SHA256
                      - ECDHE-RSA-AES128-GCM-SHA256
                      - ECDHE-ECDSA-AES256-GCM-SHA384
                      - ECDHE-RSA-AES256-GCM-SHA384
                      - ECDHE-ECDSA-CHACHA20-POLY1305
                      - ECDHE-RSA-CHACHA20-POLY1305
                      - DHE-RSA-AES128-GCM-SHA256
                      - DHE-RSA-AES256-GCM-SHA384
                    ecdh_curve:
                      - secp521r1
                      - secp384r1
                    prefer_server_ciphers: false
                    session_cache:
                      shared:
                        name: 'SSL'
                        size: '10m'
                    session_tickets: true
                    session_timeout: '1d'
                  headers:
                    add_headers:
                      - name: 'Strict-Transport-Security'
                        value: '"max-age=63072000"'
                        always: true
                      - name: 'X-Frame-Options'
                        value: '"SAMEORIGIN"'
                        always: false
                    add_trailers:
                      - name: 'Strict-Transport-Security'
                        value: '"max-age=63072000"'
                        always: true
                      - name: 'X-Frame-Options'
                        value: '"SAMEORIGIN"'
                        always: false
                  log:
                    access:
                      - path: '/var/log/nginx/{{ alias_prometheus }}_access.log'
                        format: 'main'
                    error:
                      - /var/log/nginx/{{ alias_prometheus }}_error.log
                  locations:
                    - location: '/'
                      proxy:
                        pass: 'http://127.0.0.1:{{ prometheus_port }}'
                        connect_timeout: '1s'
                        bind: false
                        set_header:
                          - field: 'Host'
                            value: '$host'
                          - field: 'X-Forwarded-For'
                            value: '$proxy_add_x_forwarded_for'
                          - field: 'X-Real-IP'
                            value: '$remote_addr'
                          - field: 'REMOTE_ADDR'
                            value: '$remote_addr'
                # ++ PROMETHEUS