prometheus_scrape_configs:
  - job_name: substrate
    metrics_path: /metrics
    # scheme: https
    # tls_config:
    #   insecure_skip_verify: true
    # basic_auth:
    #   username: "{{ nginx_username }}"
    #   password: "{{ nginx_prometheus_pw }}"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
